import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sample = readFileSync(join(root, 'data/sample-calendar.json'), 'utf8');
const license = join(root, 'LICENSE');
const disclaimer = join(root, 'DISCLAIMER.md');

const targets = [
  'js',
  'python',
  'rust',
  'dart',
  'php',
  'ruby',
  'dotnet',
  'cocoapods',
  'docker',
  'huggingface',
  'skill',
  'arcade',
  'mcp',
  'snap',
  'sourceforge',
];

for (const t of targets) {
  const dir = join(root, t);
  try {
    copyFileSync(license, join(dir, 'LICENSE'));
    copyFileSync(disclaimer, join(dir, 'DISCLAIMER.md'));
  } catch {
    /* optional dirs */
  }
}

// Dart embeds sample for offline tests
mkdirSync(join(root, 'dart/lib'), { recursive: true });
writeFileSync(
  join(root, 'dart/lib/sample_calendar.dart'),
  `/// Generated by scripts/vendor-data.mjs - do not edit by hand.\nconst String sampleCalendarJson = r'''${sample}''';\n`,
);

// Python package data
mkdirSync(join(root, 'python/src/futbol_libre_hoy/data'), { recursive: true });
writeFileSync(join(root, 'python/src/futbol_libre_hoy/data/sample-calendar.json'), sample);

console.log('Vendored LICENSE, DISCLAIMER, and sample data');
